/* ebnf.ebnf -- ebnf syntax.
 * Author: Luis Colorado <luiscoloradourcola@gmail.com>
 * Date: Tue May 15 15:49:12 EEST 2018
 */

grammar: { rule } ;

rule: IDENT ':' [ right_side ] ';' ;

right_side: [ '|' ] alternative  { '|' [ alternative ] } ;

alternative: term { term } ;

term:
      IDENT
    | STRING
    | '{' right_side '}'
    | '[' right_side ']'
    | '(' right_side ')' ;

/* END */
